#ifndef __CMD_GL_TYPES_H__
#define __CMD_GL_TYPES_H__
#include <stdint.h>
#include <Windows.h>
#define FG_INTENSE		FOREGROUND_INTENSITY
#define BG_INTENSE		BACKGROUND_INTENSITY

typedef int8_t  i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;

typedef enum {
	FG_BLACK = 0,
	FG_RED = FOREGROUND_RED,
	FG_GREEN = FOREGROUND_GREEN,
	FG_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
	FG_BLUE = FOREGROUND_BLUE,
	FG_MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
	FG_CYAN = FOREGROUND_GREEN | FOREGROUND_BLUE,
	FG_WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
} FG_COLOR;

typedef enum {
	BG_BLACK = 0,
	BG_RED = BACKGROUND_RED,
	BG_GREEN = BACKGROUND_GREEN,
	BG_YELLOW = BACKGROUND_RED | BACKGROUND_GREEN,
	BG_BLUE = BACKGROUND_BLUE,
	BG_MAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
	BG_CYAN = BACKGROUND_GREEN | BACKGROUND_BLUE,
	BG_WHITE = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
} BG_COLOR;

#endif // __CMD_GL_TYPES_H__